version: 0.2

phases:
  build:
    commands:
      - echo "🔍 Listing BuildArtifact contents:"
      - ls -la BuildArtifact || echo "BuildArtifact not found"
      - echo "🔍 Listing bk_artifact contents:"
      - ls -la bk_artifact || echo "bk_artifact not found"
      
      - echo "📁 Creating manifests directory..."
      - mkdir -p manifests
      
      - echo "📋 Copying frontend manifests..."
      - cp BuildArtifact/frontend-deployment.yaml manifests/ || echo "❌ frontend-deployment.yaml not found in BuildArtifact"
      - cp BuildArtifact/frontend-service.yaml manifests/ || echo "❌ frontend-service.yaml not found in BuildArtifact"
      
      - echo "📋 Copying backend manifests..."
      - cp bk_artifact/backend-deployment.yaml manifests/ || echo "❌ backend-deployment.yaml not found in bk_artifact"
      - cp bk_artifact/backend-service.yaml manifests/ || echo "❌ backend-service.yaml not found in bk_artifact"
      
      - echo "✅ Final manifests directory contents:"
      - ls -la manifests/

artifacts:
  files:
    - manifests/* 