version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Configuring kubectl for EKS...
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region ap-south-1 --name app-cluster-new
      - kubectl config current-context

      - echo Reading image URIs...
      - cat frontend-image-uri.txt 2>/dev/null || echo "❌ frontend-image-uri.txt not found"
      - cat backend-image-uri.txt 2>/dev/null || echo "❌ backend-image-uri.txt not found"

  build:
    commands:
      - echo "🚀 Starting deployment on `date`"

      # Update backend image
      - |
        if [ -f backend-image-uri.txt ]; then
          BACKEND_IMAGE=$(cat backend-image-uri.txt)
          echo "✅ Backend Image: $BACKEND_IMAGE"
          sed -i "s|image: .*backend:.*|image: $BACKEND_IMAGE|g" new-app/bk/backend-deployment.yaml
        fi

      # Update frontend image
      - |
        if [ -f frontend-image-uri.txt ]; then
          FRONTEND_IMAGE=$(cat frontend-image-uri.txt)
          echo "✅ Frontend Image: $FRONTEND_IMAGE"
          sed -i "s|image: .*frontend:.*|image: $FRONTEND_IMAGE|g" new-app/ft/frontend-deployment.yaml
        fi

      - echo "✅ Applying Kubernetes manifests..."
      - kubectl apply -f new-app/bk/backend-deployment.yaml
      - kubectl apply -f new-app/bk/backend-service.yaml
      - kubectl apply -f new-app/ft/frontend-deployment.yaml
      - kubectl apply -f new-app/ft/frontend-service.yaml

      - echo "⏳ Waiting for rollouts..."
      - kubectl rollout status deployment/backend --timeout=300s || echo "⚠️ Backend rollout timeout"
      - kubectl rollout status deployment/frontend --timeout=300s || echo "⚠️ Frontend rollout timeout"

  post_build:
    commands:
      - echo "✅ Deployment completed on `date`"
      - kubectl get pods -o wide
      - kubectl get svc
      - echo "✅ Verification complete"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
