version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - echo "Authenticating with EKS..."
      - aws eks update-kubeconfig --region us-east-1 --name eks-cluster-new
      - echo "Getting image URIs from build artifacts..."
      - echo "Current directory:"
      - pwd
      - echo "Listing current directory contents:"
      - ls -la
      - echo "Listing BuildArtifact directory (if exists):"
      - ls -la BuildArtifact || echo "BuildArtifact directory not found"
      - echo "Listing bk-artifact directory (if exists):"
      - ls -la bk-artifact || echo "bk-artifact directory not found"
      - echo "Checking for frontend image URI file:"
      - find . -name "frontend-image-uri.txt" -type f || echo "frontend-image-uri.txt not found anywhere"
      - echo "Checking for backend image URI file:"
      - find . -name "backend-image-uri.txt" -type f || echo "backend-image-uri.txt not found anywhere"
      - echo "Extracting image URIs..."
      - |
        if [ -f "BuildArtifact/frontend-image-uri.txt" ]; then
          FRONTEND_IMAGE=$(cat BuildArtifact/frontend-image-uri.txt)
          echo "Frontend Image found:" $FRONTEND_IMAGE
        elif [ -f "frontend-image-uri.txt" ]; then
          FRONTEND_IMAGE=$(cat frontend-image-uri.txt)
          echo "Frontend Image found in root:" $FRONTEND_IMAGE
        else
          echo "ERROR: frontend-image-uri.txt not found in any location!"
          exit 1
        fi
      - |
        if [ -f "bk-artifact/backend-image-uri.txt" ]; then
          BACKEND_IMAGE=$(cat bk-artifact/backend-image-uri.txt)
          echo "Backend Image found:" $BACKEND_IMAGE
        elif [ -f "backend-image-uri.txt" ]; then
          BACKEND_IMAGE=$(cat backend-image-uri.txt)
          echo "Backend Image found in root:" $BACKEND_IMAGE
        else
          echo "ERROR: backend-image-uri.txt not found in any location!"
          exit 1
        fi

  build:
    commands:
      - echo "Deploying frontend and backend with new images..."
      - echo "Updating frontend deployment..."
      - kubectl set image deployment/frontend frontend=$FRONTEND_IMAGE -n default
      - echo "Updating backend deployment..."
      - kubectl set image deployment/backend backend=$BACKEND_IMAGE -n default
      - echo "Waiting for rollouts to complete..."
      - kubectl rollout status deployment/frontend -n default --timeout=300s
      - kubectl rollout status deployment/backend -n default --timeout=300s

  post_build:
    commands:
      - echo "Deployment completed successfully at" $(date)
      - echo "Current deployment status:"
      - kubectl get deployments -n default
      - kubectl get pods -n default -o wide
      - kubectl get services -n default