version: 0.2

phases:
  build:
    commands:
      - mkdir -p manifests
      - cp BuildArtifact/frontend-deployment.yaml manifests/
      - cp BuildArtifact/frontend-service.yaml manifests/
      - cp bk_artifact/backend-deployment.yaml manifests/
      - cp bk_artifact/backend-service.yaml manifests/

artifacts:
  files:
    - manifests/* 