version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo Configuring kubectl for EKS...
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region ap-south-1 --name app-cluster-new
      - echo Current kubectl context:
      - kubectl config current-context

      # Read image URIs
      - echo Reading image URIs...
      - FRONTEND_IMAGE=$(cat frontend-image-uri.txt)
      - BACKEND_IMAGE=$(cat backend-image-uri.txt)
      - echo "FRONTEND_IMAGE=$FRONTEND_IMAGE"
      - echo "BACKEND_IMAGE=$BACKEND_IMAGE"

  build:
    commands:
      - echo "Updating image references in manifests..."
      - sed -i "s|image: .*frontend.*|image: $FRONTEND_IMAGE|g" new-app/ft/frontend-deployment.yaml
      - sed -i "s|image: .*backend.*|image: $BACKEND_IMAGE|g" new-app/bk/backend-deployment.yaml

      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f new-app/bk/backend-deployment.yaml
      - kubectl apply -f new-app/bk/backend-service.yaml
      - kubectl apply -f new-app/ft/frontend-deployment.yaml
      - kubectl apply -f new-app/ft/frontend-service.yaml

      - echo "Waiting for deployment rollout..."
      - kubectl rollout status deployment/backend --timeout=300s
      - kubectl rollout status deployment/frontend --timeout=300s

  post_build:
    commands:
      - echo "Deployment completed at $(date)"
      - kubectl get pods -o wide
      - kubectl get svc

artifacts:
  files:
    - '**/*'
  base-directory: '.'
