version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Configuring kubectl for EKS...
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region ap-south-1 --name app-cluster-new
      - kubectl config current-context

      - echo Reading image URIs...
      - |
        if [ -f frontend-image-uri.txt ]; then
          FRONTEND_IMAGE=$(cat frontend-image-uri.txt)
          echo "✅ Frontend image found: $FRONTEND_IMAGE"
        else
          echo "❌ frontend-image-uri.txt not found"
          exit 1
        fi
      - |
        if [ -f backend-image-uri.txt ]; then
          BACKEND_IMAGE=$(cat backend-image-uri.txt)
          echo "✅ Backend image found: $BACKEND_IMAGE"
        else
          echo "❌ backend-image-uri.txt not found"
          exit 1
        fi

  build:
    commands:
      - echo "🔧 Updating deployment manifests with new image URIs..."

      - sed -i "s|image: .*frontend:.*|image: $FRONTEND_IMAGE|g" new-app/ft/frontend-deployment.yaml
      - sed -i "s|image: .*backend:.*|image: $BACKEND_IMAGE|g" new-app/bk/backend-deployment.yaml

      - echo "🚀 Applying Kubernetes manifests..."
      - kubectl apply -f new-app/ft/frontend-deployment.yaml
      - kubectl apply -f new-app/ft/frontend-service.yaml
      - kubectl apply -f new-app/bk/backend-deployment.yaml
      - kubectl apply -f new-app/bk/backend-service.yaml

      - echo "⏳ Waiting for deployments to complete..."
      - kubectl rollout status deployment/frontend --timeout=300s || echo "⚠️ Frontend rollout may have failed"
      - kubectl rollout status deployment/backend --timeout=300s || echo "⚠️ Backend rollout may have failed"

  post_build:
    commands:
      - echo "✅ Deployment finished on `date`"
      - echo Verifying resources...
      - kubectl get pods -o wide
      - kubectl get svc
      - echo "✅ Deployment verification complete"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
