version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - echo "Authenticating with EKS..."
      - aws eks update-kubeconfig --region us-east-1 --name eks-cluster-new
      - echo "Getting image URIs from build artifacts..."
      - echo "Current directory:"
      - pwd
      - echo "Listing current directory contents:"
      - ls -la
      - echo "Searching for all possible artifact directories:"
      - find . -type d -name "*artifact*" -o -name "*Artifact*" || echo "No artifact directories found"
      - echo "Searching for frontend image URI file:"
      - find . -name "frontend-image-uri.txt" -type f -exec echo "Found: {}" \; -exec cat {} \;
      - echo "Searching for backend image URI file:"
      - find . -name "backend-image-uri.txt" -type f -exec echo "Found: {}" \; -exec cat {} \;
      - echo "Extracting image URIs..."
      - |
        FRONTEND_FILE=$(find . -name "frontend-image-uri.txt" -type f | head -1)
        if [ -n "$FRONTEND_FILE" ]; then
          FRONTEND_IMAGE=$(cat "$FRONTEND_FILE")
          echo "Frontend Image found in $FRONTEND_FILE:" $FRONTEND_IMAGE
        else
          echo "ERROR: frontend-image-uri.txt not found anywhere!"
          echo "Available files:"
          find . -name "*.txt" -type f
          exit 1
        fi
      - |
        BACKEND_FILE=$(find . -name "backend-image-uri.txt" -type f | head -1)
        if [ -n "$BACKEND_FILE" ]; then
          BACKEND_IMAGE=$(cat "$BACKEND_FILE")
          echo "Backend Image found in $BACKEND_FILE:" $BACKEND_IMAGE
        else
          echo "ERROR: backend-image-uri.txt not found anywhere!"
          echo "Available files:"
          find . -name "*.txt" -type f
          exit 1
        fi

  build:
    commands:
      - echo "Deploying frontend and backend with new images..."
      - echo "Updating frontend deployment..."
      - kubectl set image deployment/frontend frontend=$FRONTEND_IMAGE -n default
      - echo "Updating backend deployment..."
      - kubectl set image deployment/backend backend=$BACKEND_IMAGE -n default
      - echo "Waiting for rollouts to complete..."
      - kubectl rollout status deployment/frontend -n default --timeout=300s
      - kubectl rollout status deployment/backend -n default --timeout=300s

  post_build:
    commands:
      - echo "Deployment completed successfully at" $(date)
      - echo "Current deployment status:"
      - kubectl get deployments -n default
      - kubectl get pods -n default -o wide
      - kubectl get services -n default