apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  host: <BASE64_ENCODED_RDS_ENDPOINT>
  username: <BASE64_ENCODED_DB_USERNAME>
  password: <BASE64_ENCODED_DB_PASSWORD>
  dbname: <BASE64_ENCODED_DB_NAME>

# Example usage:
# echo -n "your-rds-endpoint" | base64
# echo -n "your-username" | base64
# echo -n "your-password" | base64
# echo -n "your-database-name" | base64 