apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
data:
  host: ZGF0YWJhc2UtMS5jNXc2dWVvZWlwNGwuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  username: YWRtaW4K
  password: QW5rMTUwNDAyaXRh
  dbname: bXlhcHBkYg== 